### ISSUE TITLE
Not working with ColdFusion 11

### ISSUE THREAD

**Issue by murpg** [elpete/box-ngrok#4]
Running Commandbox 3.3.0 with ColdFusion 11 on Windows and I got this error.
ERROR

```
500 Internal Server Error

C:\commandbox\cfml\modules\box-ngrok\models\NgrokService.cfc: line 68
66:                 "proto" = protocol,
67:                 "name" = name
68:             } ) );
69:         }
70:
called from C:\commandbox\cfml\modules\box-ngrok\commands\server\share\start.cfc: line 70
68:             name = serverInfo.name,
69:             port = serverInfo.port,
70:             isSSL = serverInfo.sslEnable
71:         );
72:         var tunnelUrl = tunnel.public_url;
called from C:\commandbox\cfml\system\services\CommandService.cfc: line 292
290:             // Run the command
291:             try {
292:                 var result = commandInfo.commandReference.CFC.run( argumentCollection = parameterInfo.namedParameters );
293:                 lastCommandErrored = commandInfo.commandReference.CFC.hasError();
294:             } catch( any e ){
called from C:\commandbox\cfml\system\services\CommandService.cfc: line 131
129:         var commandChain = resolveCommand( line );
130:
131:         return runCommand( commandChain, line );
132:     }
133:
called from C:\commandbox\cfml\system\Shell.cfc: line 465
463:                 }
464:             } else {
465:                 var result = variables.commandService.runCommandLine( arguments.command );
466:             }
467:
called from C:\commandbox\cfml\system\Shell.cfc: line 421
419:                 // If there's input, try to run it.
420:                 if( len( trim( line ) ) ) {
421:                     callCommand( command=line, initialCommand=true );
422:                 }
423:
called from C:\commandbox\cfml\system\Bootstrap.cfm: line 112
110:
111:         // Running the "reload" command will enter this while loop once
112:         while( shell.run( silent=silent ) ){
113:             clearScreen = shell.getDoClearScreen();
114:
500 Internal Server Error
    at lucee.runtime.tag.Http41._doEndTag(Http41.java:1266):1266
    at lucee.runtime.tag.Http41.doEndTag(Http41.java:624):624
    at lucee.runtime.tag.HttpImpl.doEndTag(HttpImpl.java:223):223
    at models.ngrokservice_cfc$cf.udfCall2(C:\commandbox\cfml\modules\box-ngrok\models\NgrokService.cfc:68):68
    at models.ngrokservice_cfc$cf.udfCall(C:\commandbox\cfml\modules\box-ngrok\models\NgrokService.cfc):-1
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
    at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:216):216
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:643):643
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524
    at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1778):1778
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:774):774
    at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1603):1603
    at modules.box_ngrok180.commands.server.share.start_cfc$cf.udfCall(C:\commandbox\cfml\modules\box-ngrok\commands\server\share\start.cfc:70):70
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
    at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:216):216
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:643):643
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524
    at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1778):1778
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:774):774
    at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1603):1603
    at system.services.commandservice_cfc$cf.udfCall1(C:\commandbox\cfml\system\services\CommandService.cfc:292):292
    at system.services.commandservice_cfc$cf.udfCall(C:\commandbox\cfml\system\services\CommandService.cfc):-1
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
    at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229
    at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:766):766
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743
    at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1593):1593
    at system.services.commandservice_cfc$cf.udfCall1(C:\commandbox\cfml\system\services\CommandService.cfc:131):131
    at system.services.commandservice_cfc$cf.udfCall(C:\commandbox\cfml\system\services\CommandService.cfc):-1
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
    at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524
    at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1761):1761
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743
    at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1593):1593
    at system.shell_cfc$cf.udfCall2(C:\commandbox\cfml\system\Shell.cfc:465):465
    at system.shell_cfc$cf.udfCall(C:\commandbox\cfml\system\Shell.cfc):-1
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
    at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:216):216
    at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:775):775
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:774):774
    at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1603):1603
    at system.shell_cfc$cf.udfCall2(C:\commandbox\cfml\system\Shell.cfc:421):421
    at system.shell_cfc$cf.udfCall(C:\commandbox\cfml\system\Shell.cfc):-1
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
    at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:216):216
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:643):643
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524
    at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1778):1778
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:774):774
    at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1603):1603
    at commandbox.cfml.system.bootstrap_cfm$cf.call(C:\commandbox\cfml\system\Bootstrap.cfm:112):112
    at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:954):954
    at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:906):906
    at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:225):225
    at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:37):37
    at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2265):2265
    at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2228):2228
    at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:456):456
    at lucee.runtime.engine.CFMLEngineImpl.cli(CFMLEngineImpl.java:760):760
    at lucee.loader.engine.CFMLEngineWrapper.cli(CFMLEngineWrapper.java:267):267
    at luceecli.CLIMain.run(CLIMain.java:223):223
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method):-2
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62):62
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43):43
    at java.lang.reflect.Method.invoke(Method.java:497):497
    at cliloader.LoaderCLIMain.execute(LoaderCLIMain.java:205):205
    at cliloader.LoaderCLIMain.main(LoaderCLIMain.java:698):698

CommandBox:adminrewrite>```

**Comment by bdw429s** [comment]
I would put in some debugging code there in the service @murpg .  Remove the `throwOnError=true` temporarily and dump out the results of the HTTP call like so:

```
systemOutput( cfhttp, true );
```

**Comment by murpg** [comment]
@bdw429s I tried that with Lucee just removing the throw on error and that worked. Will report back on Adobe CF11

**Comment by bdw429s** [comment]
@murpg When you say it worked, do you mean that the tunnel opened successfully and worked, or the error simply didn't happen?  The suggestion to remove the `throwOnError` was only to be used in conjunction with additional debugging information.

**Comment by murpg** [comment]
@bdw429s what I meant was the tunnel opened and correctly and created an Ngrok tunnel for me. Also, I just tried it with CF11. If I remove the throwonerror=true it creates the tunnel and I can view resources. The interesting thing is that I get another error when I try and hit the app. I suspect that it needs a valid keystore added in the CFServer.

**Comment by bdw429s** [comment]
Interesting that it works.  cfhttp should only be throwing an exception if the status code is coming back 5xx.   That is where the debugging would come in to see what the actual response is coming back.  Of course, it's also possible that whatever the issue was has cleared up and the removal of the `throwOnError` parameter isn't related to it's working state.

**Comment by elpete** [comment]
@bdw429s are you able to share CF servers successfully?

**Comment by bdw429s** [comment]
Yes.  I just successfully tested a tunnel to Adobe CF 11 and 2016.  @murpg said he was able to get it working too eventually,, but I'm unclear on whether it was related to his code modifications or just the gremlins were asleep.

**Comment by elpete** [comment]
Okay.  I'm going to close this one for now, then.  Thanks.
